version: "3.1"

services:
  app:
    build: .
    volumes:
      - ./:/app
    command: go run main.go
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - MONGODB_URI=mongodb://database:27017
  database:
    image: mongo:latest
    container_name: database
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
