version: "3.1"

services:
  mongo:
    image: mongo:latest
    container_name: rest-api-template-golang-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
